eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
              
management:
    endpoint:
        web:
            exposure:
                include: info,health
    info:
        env:
            enabled: true
            
