            
spring:
    zipkin:
        base-url: http://zipkin:9411/
        enabled: true
        
management:
    endpoints:
        web:
            exposure:
                include: info,health
    info:
        env:
            enabled: true
            
